---
defaults:
  vars:
    host_key_checking: false
- hosts: all
  gather_facts: no

  tasks:
    - name: Install Yum Package "{{package_name}}"
      apt:
        name: "{{package_name}}"
        state: latest
      become: yes
